### ISSUE TITLE
make topics&content align with navigation bar

### ISSUE THREAD

**Issue by mrzl** [LacunaLab/lacunalab-website#11]

**Comment by mrzl** [comment]
this offset is what im talking about. it differs on various screen sizes though

![2016-01-03 18_56_31-adobe photoshop cs6](https://cloud.githubusercontent.com/assets/1453951/12079969/2c08c8ea-b24c-11e5-9364-3a4febc6de62.jpg)

**Comment by jvolker** [comment]
Already solved for desktop screens in dev_grid branch.

**Comment by jvolker** [comment]
Solved for all screen sizes on dev_grid branch.
