### ISSUE TITLE
check 960 grid thingy

### ISSUE THREAD

**Issue by thomesh** [LacunaLab/lacunalab-website#18]

**Comment by jvolker** [comment]
I need properly scaled mockups to be able to be exact here. Now waiting for 72 dpi and 144dpi exports of lacuna-web-1-landing.jpg and lacuna-web-3-withgrid.jpg from Aurelia.

**Comment by jvolker** [comment]
Got he mockup! Looks like most elements are larger compared to it. 
I'm going to export properly sized JPEGs and provide them, so we can stick closer to the well thought through mockup when writing CSS.
