### ISSUE TITLE
navigation: update active section based on vertical scroll position

### ISSUE THREAD

**Issue by thomesh** [LacunaLab/lacunalab-website#24]

**Comment by hamoid** [comment]
Bootstrap comes with a library to achieve this https://getbootstrap.com/javascript/#scrollspy but I don't have the patience to make it work.

**Comment by hamoid** [comment]
[rant warning after 5 hours trying to make this work]
I vote for doing a website like this http://bettermotherfuckingwebsite.com/
Otherwise let me know when this one is ready. 
I feel like life is too short to waste time doing "web development".

**Comment by mrzl** [comment]
Well, I agree with you, but now the designers put so much effort into the design. I doubt I'll make this one work here, but I thought it already worked? We could prolly ignore web view. Bah, fuck web development. Fuck screen sizes and all that fuck.

**Comment by thomesh** [comment]
:D Fuck the designers 😜

2016-01-14 18:09 GMT+01:00 Marcel Schwittlick <notifications@github.com>:
