### ISSUE TITLE
latest: properly position/style navigation-arrows

### ISSUE THREAD

**Issue by thomesh** [LacunaLab/lacunalab-website#25]

**Comment by transfluxus** [comment]
yo design. do you have the arrows of part of a font?

**Comment by jvolker** [comment]
You should find and be able to extract it from the PDF version of the mockup (hope it's the latest one): https://trello-attachments.s3.amazonaws.com/5575f6d7fda09c5e9a6a2ed0/5576c9d8c793fba3d88e2b8d/fa6414c7ec67e78d8599903f09a30594/lacuna-web-mockup_part1_new.pdf

**Comment by jvolker** [comment]
I extracted the arrows and put them in the img folder.

**Comment by euGs** [comment]
They should be black, no shadow and the right one seems to be lost under the image
