### ISSUE TITLE
header: adjust appearance of logo (and text within it) on top left

### ISSUE THREAD

**Issue by thomesh** [LacunaLab/lacunalab-website#37]
At scroll top: no logo top left (blank)
With large logo partially cut off at top: logo top left visible
Large logo invisible: top left logo gets text

**Comment by jvolker** [comment]
Could somebody please describe the issue in detail?

**Comment by hamoid** [comment]
Maybe it was "according to vertical scroll position" and not "according to mouse cursor position"?

**Comment by hamoid** [comment]
Posting images here would help understand the issue and get it fixed.
