### ISSUE TITLE
map overlay bug

### ISSUE THREAD

**Issue by mrzl** [LacunaLab/lacunalab-website#4]
the text overlay over the map at the bottom. it works on my notebook with fullscreen browser, though when scaling the site down a bit, the overlay disappears and moves downwards.

@transfluxus you've been working on this, no?

**Comment by hamoid** [comment]
I think there were several issues with smaller screen sizes. We haven't worked on those yet, afaik.

**Comment by mrzl** [comment]
yeah. i just tried, but it works fine now.
