### ISSUE TITLE
landing: needs a working e-mail address

### ISSUE THREAD

**Issue by jvolker** [LacunaLab/lacunalab-website#40]

**Comment by hamoid** [comment]
The e-mail is there. But who will check that e-mail account? Should it be forwarded to our mailing list?

**Comment by euGs** [comment]
For now, that would be great. When we need a different solution we can deal
with that then

**Comment by hamoid** [comment]
Who can add to the googlegroup the e-mail listed at the bottom of
http://lacunalab.org/ ? I tried writing to lacunalab+subscribe@..., but
it did not work.

Once the e-mail is added, I can forward e-mails to our mailing list.

**Comment by euGs** [comment]
I tried too but looks like I don't have sufficient permissions

**Comment by somaholiday** [comment]
I can add it, but it will have the side effect that info@lacunalab.org will
receive every mail we send internally, which could end up in an email
infinite loop...

**Comment by somaholiday** [comment]
Ah, I can make it so that member of the googlegroup receives no email.
Done. :)

**Comment by euGs** [comment]
Unicorns!

**Comment by hamoid** [comment]
Seems to be working now. E-mails to our public address are forwarded to all members.
