### ISSUE TITLE
landing: change map link

### ISSUE THREAD

**Issue by jvolker** [LacunaLab/lacunalab-website#41]
change to this specific link of Lacuna Labs on GoogleMaps: https://www.google.de/maps/place/Lacuna+Lab+e.V./@52.4964535,13.4185438,17z/data=!4m7!1m4!3m3!1s0x47a84fcb3cd2a77f:0xdb72cb1e8fca7615!2sPaul-Lincke-Ufer+44A,+10999+Berlin!3b1!3m1!1s0x0000000000000000:0x12bf74d2cb2671f3

**Comment by hamoid** [comment]
I don't understand this issue. What should be changed? The website uses mapbox and openstreetmap to embed a map. Where should this link be used?

**Comment by euGs** [comment]
No, the issue was to make sure that the entry on google maps for Lacuna Lab includes our correct URL, i.e. lacunalab.org. I already did that but didn't close the issue. Doing that now.

**Comment by jvolker** [comment]
The issue is not about the map. It's about the link to GoogleMaps in the text of the landing section. 
> Find us in Kreuzberg, Berlin
currently links to "Paul-Lincke-Ufer 44A" instead of the GoogleMaps entry of "Lacuna Lab".
