### ISSUE TITLE
credits at the bottom

### ISSUE THREAD

**Issue by mrzl** [LacunaLab/lacunalab-website#5]
at the bottom, we got credits about using some icons. if im not completely mistaken, it's only the vimeo/twitter/facebook/tumblr logo. can't we just make these flat logos ourselves and get rid of the credits?

**Comment by hamoid** [comment]
We can use https://fortawesome.github.io/Font-Awesome/icons/ (look at the get started). That way we don't need credits for that, and we have all icons easily available.

**Comment by mrzl** [comment]
nice!
